#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
from ToolBox.weather import weather_forecast, find_woeid

if __name__ == '__main__':
    description = "Give the weather forecast"
    #Create the parser object
    parser = argparse.ArgumentParser(description = description)

    #Take in the city name
    parser.add_argument('--city',
                        type = str,
                        help = 'The city you want to find a weather forecast for',
                        required = True)
    args = parser.parse_args()
    city = args.city

    forecast = weather_forecast(find_woeid(city))
    print(f"The weather forecast for {city} is {forecast}")
    # description = 'stkrgcp_description'
    # parser = argparse.ArgumentParser(description=description)
    # parser.add_argument('--coords',
    #                     nargs='+',
    #                     help='list of coordinates',
    #                     required=False)
    # parser.add_argument('--prod',
    #                     action='store_true',
    #                     default=False,
    #                     help='Example here')
    # args = parser.parse_args()
    # lon1, lat1, lon2, lat2 = args.coords
    # dist = haversine(float(lon1), float(lat1), float(lon2), float(lat2))
    # print(colored("###### Distance ######", "blue"))
    # print(colored(dist, "red"))
